# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NKM8eVRKPaE1K0dpA8jxhfSyyMJDrf5Z
"""

from train import accuracy
import numpy as np



def gridsearch(model,trainset,precision,epsilon,phi=1):
  solu=1,1,1
  accu_max=accuracy(model(1,1,1),trainset)
  for alpha in range(1,2,precision):
    for beta in range(1,2,precision):
      for gama in range(1,2,precision):
        if np.abs(alpha*beta**2*gama**2 - 2)<=epsilon:
          accu = accuracy(model(alpha,beta,gama),trainset)
          if accu>accu_max:
            accu_max= accu
            solu=alpha,beta,gama
    return solu

